### ISSUE TITLE
Create Templates for API Tests

### ISSUE THREAD

**Issue by dmgaldi** [VEuPathDB/example-jaxrs-container-service#12]
## Overview
We identified a testing gap for some of our docker services. On 05/03/2022, we discussed adding API tests to user dataset import service to address some latent bugs.

We currently use RestAssured for [WDK API tests](https://github.com/VEuPathDB/wdk-api-test) that are run as a part of the QA release. There is work here to figure out where the docker API tests will live (likely in the repo under an api-test directory?), how they will be run (at least manually and documented in example repo/readme but ideally automatically on release).

## Subtasks
Note that this can be broken down into multiple tasks. Below is a summary of the subtasks:

- [ ] Create a test suite using RestAssured to one of our docker-services and verify that it works correctly
- [ ] Integrate test suite into this template repo (assuming tests will live in the service repo)
- [ ] Integrate test suite into Jenkins continuous integration with the help of Systems (or investigate self-hosted GitHub runner)
- [ ] (Optional) Create empty test suites or rudimentary suites in other docker services to make it easier for devs to add tests as they develop
